### ISSUE TITLE
Error when initilizating network

### ISSUE THREAD

**Issue by pedrobagatin** [astuff/ibeo_lux#11]
I get the following error when trying to connect to the IBEO LUX 4L:

_[ WARN] [1552976276.733442993]: Ibeo LUX - Unable to connect to sensor at 192.168.0.1: -1 - Initialization of the network interface failed._

When using windows it worked by 192.168.0.1 address but somehow in ubuntu it doesn't work.

Configuration of the system is Ibeo -> Ethernet (HUB) -> Laptop

Ethernet(HUB) was changed to 192.168.0.2
Laptop ip is 192.168.0.3

Is there any software I should install to start the network communication?

**Comment by JWhitleyAStuff** [comment]
@pedrobagatin - Have you verified that your IP address in Ubuntu is correctly assigned to the right interface? The "initialization of the network interface failed" message indicates that this is a problem with your network interface in Ubuntu. Are you sure that the driver is loaded and working for your network card in Ubuntu? You can check on the list of interfaces and the IP addresses assigned to them with the command `ifconfig` on the terminal.

**Comment by pedrobagatin** [comment]
> @pedrobagatin - Have you verified that your IP address in Ubuntu is correctly assigned to the right interface? The "initialization of the network interface failed" message indicates that this is a problem with your network interface in Ubuntu. Are you sure that the driver is loaded and working for your network card in Ubuntu? You can check on the list of interfaces and the IP addresses assigned to them with the command `ifconfig` on the terminal.

I fixed it, I think first time when trying to run I was using one network wi-fi and another network ethernet. Disabling wifi from the another network made it to work probably, thanks.
