### ISSUE TITLE
the problem of none message is published 

### ISSUE THREAD

**Issue by melodynk** [astuff/ibeo_lux#13]
Hi,I would like to use this ROS package to communicate the IBEO lux 4layers sensor.   
But I encounter some problems.    
My IBEO's IP is 192.168.1.12,   and the port number is 12002,
I set linux‘s IP through the manual method as 192.168.1.10,    like the fugure_01 below.
I check the ethernet configureation through the "ifconfig" command,    like the figure_02 below.
I start-up the IBEO package thorugh : roslaunch ibeo_lux.launch,   like the figure_03 below
Finally when I check what the message prints. it will give none output , like the figure_04 below
I check the node communication through rqt_graph,   like the figure_05 below
I just would like to know which step probably occurs the error and makes none output.
Thanks so much!
![figure_01](https://user-images.githubusercontent.com/37090372/55221559-afab3e80-5244-11e9-90d3-e506227c77fe.png)
![figure_02](https://user-images.githubusercontent.com/37090372/55221571-b8037980-5244-11e9-87b5-338d3efe399b.png)
![figure_03](https://user-images.githubusercontent.com/37090372/55221621-d8cbcf00-5244-11e9-9f07-e6aeeaa16824.png)
![figure_04](https://user-images.githubusercontent.com/37090372/55221654-ee40f900-5244-11e9-9173-0550e9c1de06.png)
![figure_05](https://user-images.githubusercontent.com/37090372/55221672-fac55180-5244-11e9-898b-77de210278d4.png)

**Comment by JWhitleyAStuff** [comment]
@melodynk - Please try running the launch file with `--screen` at the end of the command and see if you receive any additional output.

**Comment by JWhitleyAStuff** [comment]
Also, in the screenshots above, your Network Manager window shows a PC IP of 192.168.1.10 while your `ifconfig` output shows an IP address of 192.168.1.11. Make sure you do not have two interfaces configured in the same ip subnet.

**Comment by melodynk** [comment]
Hi Mr Whitley. After I execute the command  roslaunch ibeo_lux.launch --screen,   the output information is shown in the figure below
And I found that I upload a wrong file of figure02.the ifconfig output sholud be 192.168.1.10.correspondly with the setting page shown figure_01.they are both 192.168.1.10
![Screenshot from 2019-04-01 11-01-12](https://user-images.githubusercontent.com/37090372/55301335-a9000f80-546e-11e9-89fd-542415c57398.png)

**Comment by melodynk** [comment]
Hi,Mr. Whitley,I finally handle the problem.However one more thing is that ,when I visualize the target with the ROS RVIZ.It seems to have lots of noise results, As is shown in the figure below.Do you have any solution scheme to suppress the noise and background?
![Uploading Screenshot from 2019-04-01 16-04-44.png…]()

**Comment by melodynk** [comment]
Hi,Mr. Whitley,I finally handle the problem.However one more thing is that ,when I visualize the target with the ROS RVIZ.It seems to have lots of noise results, As is shown in the figure below.Do you have any solution scheme to suppress the noise and background?
![Screenshot from 2019-04-01 16-04-44](https://user-images.githubusercontent.com/37090372/55312703-ba5e1180-5498-11e9-984d-90cda9283912.png)

**Comment by JWhitleyAStuff** [comment]
@melodynk - Most of the objects that it detects will be of type "Unknown Big" and "Unknown Small." In RViz, if you show the configuration panel and expand the Marker type, you should be able to uncheck those types.
